// <auto-generated />
using System;
using DataGo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataGo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataGoDbContext))]
    partial class DataGoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataGo.Domain.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("centers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000200"),
                            Code = "MDE-C001",
                            IsActive = true,
                            Name = "Centro Medellín Norte"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            Code = "MDE-C002",
                            IsActive = true,
                            Name = "Centro Medellín Sur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            Code = "MDE-C003",
                            IsActive = true,
                            Name = "Centro Medellín Oriente"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            Code = "MDE-C004",
                            IsActive = true,
                            Name = "Centro Medellín Occidente"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204"),
                            Code = "MDE-C005",
                            IsActive = true,
                            Name = "Centro Medellín Centro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000205"),
                            Code = "MDE-C006",
                            IsActive = true,
                            Name = "Centro Laureles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000206"),
                            Code = "MDE-C007",
                            IsActive = true,
                            Name = "Centro El Poblado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000207"),
                            Code = "MDE-C008",
                            IsActive = true,
                            Name = "Centro Belén"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000208"),
                            Code = "MDE-C009",
                            IsActive = true,
                            Name = "Centro Guayabal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000209"),
                            Code = "MDE-C010",
                            IsActive = true,
                            Name = "Centro La América"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000210"),
                            Code = "MDE-C011",
                            IsActive = true,
                            Name = "Centro Robledo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000211"),
                            Code = "MDE-C012",
                            IsActive = true,
                            Name = "Centro Castilla"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000212"),
                            Code = "MDE-C013",
                            IsActive = true,
                            Name = "Centro Aranjuez"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000213"),
                            Code = "MDE-C014",
                            IsActive = true,
                            Name = "Centro Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000214"),
                            Code = "MDE-C015",
                            IsActive = true,
                            Name = "Centro Manrique"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000215"),
                            Code = "MDE-C016",
                            IsActive = true,
                            Name = "Centro San Javier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000216"),
                            Code = "MDE-C017",
                            IsActive = true,
                            Name = "Centro Doce de Octubre"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000217"),
                            Code = "MDE-C018",
                            IsActive = true,
                            Name = "Centro Villa Hermosa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000218"),
                            Code = "MDE-C019",
                            IsActive = true,
                            Name = "Centro Santa Cruz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000219"),
                            Code = "MDE-C020",
                            IsActive = true,
                            Name = "Centro Popular"
                        });
                });

            modelBuilder.Entity("DataGo.Domain.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Colombia"
                        });
                });

            modelBuilder.Entity("DataGo.Domain.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsRural")
                        .HasColumnType("boolean");

                    b.Property<string>("MainRoadCardinality")
                        .HasColumnType("text");

                    b.Property<string>("MainRoadLetter")
                        .HasColumnType("text");

                    b.Property<string>("MainRoadNumber")
                        .HasColumnType("text");

                    b.Property<string>("MainRoadType")
                        .HasColumnType("text");

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuralAddress")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryRoadCardinality1")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryRoadCardinality2")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryRoadLetter")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryRoadNumber1")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryRoadNumber2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("NeighborhoodId");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("DataGo.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Antioquia"
                        });
                });

            modelBuilder.Entity("DataGo.Domain.ModernChannelCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("modern_channel_customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000301"),
                            DocumentNumber = "1010000001",
                            DocumentType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000302"),
                            DocumentNumber = "1010000002",
                            DocumentType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000303"),
                            DocumentNumber = "2010000001",
                            DocumentType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000304"),
                            DocumentNumber = "900123456",
                            DocumentType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000305"),
                            DocumentNumber = "901234567",
                            DocumentType = 2
                        });
                });

            modelBuilder.Entity("DataGo.Domain.Municipality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("municipalities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            DepartmentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Medellín"
                        });
                });

            modelBuilder.Entity("DataGo.Domain.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransportZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Name");

                    b.HasIndex("TransportZoneId");

                    b.ToTable("neighborhoods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000100"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Laureles",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Conquistadores",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Florida Nueva",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Estadio",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Los Colores",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Carlos E. Restrepo",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "El Poblado",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Provenza",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Manila",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Astorga",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000110"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Castropol",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000111"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Santa María de los Ángeles",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000112"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Belén",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000113"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Belén Rosales",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000114"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Belén La Palma",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000115"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Belén Fátima",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000116"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Belén Granada",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000117"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Los Alpes",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000118"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "La América",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000119"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Santa Lucía",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000120"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Calasanz",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000121"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "La Floresta",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000122"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Santa Mónica",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000123"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Robledo",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000124"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Pilarica",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000125"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Córdoba",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000126"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "López de Mesa",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000127"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Boston",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000128"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Bomboná",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000129"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Prado",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000130"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Villa Nueva",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000131"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Buenos Aires",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000132"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Miraflores",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000133"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "La Milagrosa",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000134"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Aranjuez",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000135"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Manrique Central",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000136"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Campo Valdés",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000137"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Moravia",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000138"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Castilla",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000139"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Pedregal",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000140"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Boyacá Las Brisas",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000141"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Guayabal",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000142"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Cristo Rey",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000143"),
                            MunicipalityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Trinidad",
                            TransportZoneId = new Guid("00000000-0000-0000-0000-000000000013")
                        });
                });

            modelBuilder.Entity("DataGo.Domain.ResidentialCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExtendedLegalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text");

                    b.Property<string>("PaymentCondition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhoneExtension")
                        .HasColumnType("text");

                    b.Property<short>("Stratum")
                        .HasColumnType("smallint");

                    b.Property<int>("TaxClass")
                        .HasColumnType("integer");

                    b.Property<int>("Treatment")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationDigit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("residential_customers", (string)null);
                });

            modelBuilder.Entity("DataGo.Domain.TransportZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("transport_zones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Code = "MDE-NORTE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Code = "MDE-NORORIENTE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Code = "MDE-CENTRO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Code = "MDE-CENTRO-OCCIDENTE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Code = "MDE-OCCIDENTE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Code = "MDE-SUROCCIDENTE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Code = "MDE-SUR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Code = "MDE-SURORIENTE"
                        });
                });

            modelBuilder.Entity("DataGo.Domain.CustomerAddress", b =>
                {
                    b.HasOne("DataGo.Domain.ResidentialCustomer", null)
                        .WithOne("Address")
                        .HasForeignKey("DataGo.Domain.CustomerAddress", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataGo.Domain.Neighborhood", null)
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataGo.Domain.Department", b =>
                {
                    b.HasOne("DataGo.Domain.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataGo.Domain.Municipality", b =>
                {
                    b.HasOne("DataGo.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataGo.Domain.Neighborhood", b =>
                {
                    b.HasOne("DataGo.Domain.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataGo.Domain.TransportZone", null)
                        .WithMany()
                        .HasForeignKey("TransportZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataGo.Domain.ResidentialCustomer", b =>
                {
                    b.HasOne("DataGo.Domain.Center", null)
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataGo.Domain.ResidentialCustomer", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
