@DataGo.Api_HostAddress = http://localhost:5124

GET {{DataGo.Api_HostAddress}}/api/health
Accept: application/json

###

GET {{DataGo.Api_HostAddress}}/api/catalogs/centers
Accept: application/json

###

GET {{DataGo.Api_HostAddress}}/api/catalogs/neighborhoods?query=Laureles
Accept: application/json

###

GET {{DataGo.Api_HostAddress}}/api/residential-customers?search=cliente
Accept: application/json

###
